# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name_plural': '个人博客'},
        ),
    ]
